# Generated by Django 3.1.7 on 2021-09-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210903_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
